FROM node:15.8.0-alpine as build

WORKDIR /app

COPY package.json .
COPY package-lock.json .
COPY tsconfig.build.json .

COPY scripts/ ./scripts/
COPY common/ ./common/
COPY client/ ./client/

RUN npm ci

WORKDIR /app/common
RUN npm run build-linux

WORKDIR /app/client
RUN npm run build



FROM nginx:alpine

COPY nginx/nginx.conf /etc/nginx/nginx.conf
# /etc/nginx/conf.d/default.conf

WORKDIR /usr/share/nginx/html

COPY --from=build /app/client/build .

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
