version: "3.9"
services:
  server:
    build: 
      dockerfile: "Dockerfile.server"
      context: .
    container_name: server
    ports: 
      - 4000:4000
  client:
    build: 
      context: .
      dockerfile: "Dockerfile.client"
    depends_on: 
      - server
    ports: 
      - 3000:80